const data = [
  {
    id: 1,
    name: 'Lily',
    postName: 'Lily',
    image: require('../images/profil.jpg'),
    postImage: require('../images/portakal.jpg'),
    like: 25,
    newsPost: 'Found blue Oranges in North Carolina',
    comment: 'Interesting',
    explanation: 'Blue Oranges...',
    time: '1 hour ago',
    timeStory: '1s',
    islike: false,
    news: 'After months of negotiations, President Joe Biden and Republican Speaker of the House Kevin McCarthy finally reached a deal to raise the amount of money the US can borrow, avoid a default on the national debt, and limit federal spending for the next two years.Now the pair are busy selling their weekend agreement to Congress. First up is the US House of Representatives, which is scheduled to hold a vote on the agreement on Wednesday evening. Republican and Democratic leaders there believe that even with some defections on the left and right, they have the votes to pass a bill - perhaps by a comfortable margin.'
  },
  {
    id: 2,
    name: 'Marshal',
    postName: 'Marshal',
    image: require('../images/macellan.jpg'),
    postImage: require('../images/fintech.jpeg'),
    like: 360,
    newsPost: 'Found blue Oranges in North Carolina',
    comment: 'Interesting',
    explanation: 'FinTech',
    time: '2 hours ago',
    timeStory: '53d',
    islike: false,
    news: 'After months of negotiations, President Joe Biden and Republican Speaker of the House Kevin McCarthy finally reached a deal to raise the amount of money the US can borrow, avoid a default on the national debt, and limit federal spending for the next two years.Now the pair are busy selling their weekend agreement to Congress. First up is the US House of Representatives, which is scheduled to hold a vote on the agreement on Wednesday evening. Republican and Democratic leaders there believe that even with some defections on the left and right, they have the votes to pass a bill - perhaps by a comfortable margin.'
  },
  {
    id: 3,
    name: 'Robin',
    postName: 'Robin',
    image: require('../images/ezgiceylan.jpeg'),
    postImage: require('../images/oje.jpg'),
    like: 120,
    newsPost: 'Found blue Oranges in North Carolina',
    comment: 'Interesting',
    explanation: 'Pretty Nails:)',
    time: '3 hours ago',
    timeStory: '2s',
    islike: false,
    news: 'After months of negotiations, President Joe Biden and Republican Speaker of the House Kevin McCarthy finally reached a deal to raise the amount of money the US can borrow, avoid a default on the national debt, and limit federal spending for the next two years.Now the pair are busy selling their weekend agreement to Congress. First up is the US House of Representatives, which is scheduled to hold a vote on the agreement on Wednesday evening. Republican and Democratic leaders there believe that even with some defections on the left and right, they have the votes to pass a bill - perhaps by a comfortable margin.'
  },
  {
    id: 4,
    name: 'Ted',
    postName: 'Ted',
    image: require('../images/cat.jpg'),
    postImage: require('../images/catPost.jpg'),
    like: 160,
    newsPost: 'Found blue Oranges in North Carolina',
    comment: 'Interesting',
    explanation: 'Cat',
    time: '5 hours ago',
    timeStory: '3s',
    islike: false,
    news: 'After months of negotiations, President Joe Biden and Republican Speaker of the House Kevin McCarthy finally reached a deal to raise the amount of money the US can borrow, avoid a default on the national debt, and limit federal spending for the next two years.Now the pair are busy selling their weekend agreement to Congress. First up is the US House of Representatives, which is scheduled to hold a vote on the agreement on Wednesday evening. Republican and Democratic leaders there believe that even with some defections on the left and right, they have the votes to pass a bill - perhaps by a comfortable margin.'
  },
  {
    id: 5,
    name: 'Barney',
    postName: 'Barney',
    image: require('../images/alternatif.png'),
    postImage: require('../images/Afiş.png'),
    like: 220,
    newsPost: 'Found blue Oranges in North Carolina',
    comment: 'Interesting',
    explanation: 'Finance',
    time: '8 hours ago',
    timeStory: '6s',
    islike: false,
    news: 'After months of negotiations, President Joe Biden and Republican Speaker of the House Kevin McCarthy finally reached a deal to raise the amount of money the US can borrow, avoid a default on the national debt, and limit federal spending for the next two years.Now the pair are busy selling their weekend agreement to Congress. First up is the US House of Representatives, which is scheduled to hold a vote on the agreement on Wednesday evening. Republican and Democratic leaders there believe that even with some defections on the left and right, they have the votes to pass a bill - perhaps by a comfortable margin.'
  },
  {
    id: 6,
    name: 'Ranjit',
    postName: 'Ranjit',
    image: require('../images/bfy.png'),
    postImage: require('../images/bfyPost.jpg'),
    like: 150,
    newsPost: 'Found blue Oranges in North Carolina',
    comment: 'Interesting',
    explanation: 'Cars',
    time: '24 hours ago',
    timeStory: '24s',
    islike: false,
    news: 'After months of negotiations, President Joe Biden and Republican Speaker of the House Kevin McCarthy finally reached a deal to raise the amount of money the US can borrow, avoid a default on the national debt, and limit federal spending for the next two years.Now the pair are busy selling their weekend agreement to Congress. First up is the US House of Representatives, which is scheduled to hold a vote on the agreement on Wednesday evening. Republican and Democratic leaders there believe that even with some defections on the left and right, they have the votes to pass a bill - perhaps by a comfortable margin.'
  },
];
export default data;
